version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alice
      - MONGO_INITDB_ROOT_PASSWORD=super-secret-password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  produit-service:
    image: produit-service:latest
    container_name: produit-service
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network

  commande-service:
    image: commande-service:latest
    container_name: commande-service
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: host

volumes:
  mongodb_data: